
name: CI/CD Pipeline - Frontend (EKS)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1 

      - name: Iniciar sesión en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Construir, etiquetar y publicar imagen en ECR
        working-directory: ./front_despacho
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: examen/frontdevops
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            --build-arg VITE_URL_VENTAS=${{ secrets.URL_VENTAS }} \
            --build-arg VITE_URL_DESPACHOS=${{ secrets.URL_DESPACHOS }} \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Actualizar Kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name eks-examen 

      - name: Desplegar Frontend en Kubernetes
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          TAG: ${{ github.sha }}
        run: |
          kubectl apply -f k8s/frontend.yaml
          
          kubectl set image deployment/frontend-deployment frontend=$ECR_REGISTRY/examen/frontdevops:$TAG
          kubectl rollout status deployment/frontend-deployment